### ISSUE TITLE
Infinite scrolling on app info screen

### ISSUE THREAD

**Issue by TheHighTide** [vgmoose/hbas#110]
**Describe the bug**
When I tap on an app in the app list and go to the screen that has all the info, I can scroll down infinitely. Even when I toggle expanded info it still does the same thing. 

**Platform:**
Wii U

**To Reproduce**
1. Go to hbappstore on Wii U
2. Click on any app
3. Hold the DPAD DOWN button and watch all the contents leave the screen

**Comment by vgmoose** [comment]
Thanks, it's a bug with Chesto not having a southern bound on vertical scrollviews. We do know what the height of this pane should be, so it should be possible to have a stop there.

Worth noting though, that Chesto/hb-appstore's input priority are the touch controls, so if the southern boundary can't work in a satisfying way via touch then this might take longer to fix.

**Comment by TheHighTide** [comment]
Cool

**Comment by vgmoose** [comment]
Okay, ended up just manually limiting the scroll on the app details page specifically, not in Chesto itself. Pages that are too short to scroll should also not scroll at all, unless read more is expanded.

Try on nightlies: https://nightly.link/fortheusers/hb-appstore/workflows/main/main

Leaving this issue open until the 2.4 release. Also there are cursor changes on both this screen and in the App list view, it animates while scrolling with the joystick now instead of flickering down. Hopefully this makes using the joystick to navigate feel better overall.

**Comment by vgmoose** [comment]
Actually, I am going to close this issue as 2.4 gets ready, to make it easier to track the open issues. If you're able, let me know if there's any issues with the new scrolling bounds (on both App list and App details).
