### ISSUE TITLE
Garbled non-ASCII characters

### ISSUE THREAD

**Issue by GewoonLeonYT** [vgmoose/hbas#115]
**Describe the bug**
Non-ASCII characters are garbled on the AppDetails screen, but work fine elsewhere

**Platform:**
Affects all platforms

**To Reproduce**
Using a custom repo with the following repo.json: 
```json
{
    "packages": [
        {
            "name": "test",
            "title": "Testin’",
            "author": "test",
            "version": "1.0.0",
            "details": "Testin’"
        }
    ]
}
```
And going the app details page, the apostrophe "’" (U+2019) becomes garbled; this also happens to other non-ASCII characters.
![2024-01-30_01-56](https://github.com/fortheusers/hb-appstore/assets/35887230/0d34fea9-96b1-4fdd-b99f-41be43fc2b5d)
On other screens and the title at the top of the app details it's fine.
![2024-01-30_01-44](https://github.com/fortheusers/hb-appstore/assets/35887230/40032b5c-4418-4a9e-95c7-9dc982c89e93)

**Comment by vgmoose** [comment]
Thank you for the report and example repo to reproduce! This appears to be fixed now with the new localization support (which also supports more UTF8 characters) in: https://github.com/fortheusers/hb-appstore/commit/b22b24968ac76af8fc01b28b29d3554ca8d1bff7. The very specific change that fixes this page is the use of <code>TTF_Render<b>UTF8</b>_Blended_Wrapped</code> instead of `TTF_RenderText_Blended_Wrapped` in [Chesto's TextElement](https://github.com/fortheusers/chesto/blob/main/src/TextElement.cpp#L108).

Image of App Details after those changes:

![Screenshot 2024-04-14 at 5 53 37 PM](https://github.com/fortheusers/hb-appstore/assets/2467473/a2b1e417-44c2-4d92-b060-d6df4c0f06f5)
