### ISSUE TITLE
HB App Store unable to connect to the internet.

### ISSUE THREAD

**Issue by Ryuhouji** [vgmoose/hbas#76]
**Describe the bug**
I just installed this nro version on my switch, and when I launch it, it immediately says "Couldn't connect to the Internet!" The system settings internet options are saying connection is successful, and the nxthemes store  and youtube are working just fine, so my switch definitely has a connection.

**Platform:**
Switch

**To Reproduce**
...Launch the app

**Comment by Vergil55555** [comment]
Me pasa tan bien lo mismo

**Comment by fennectech** [comment]
its likely down to mitigate the threat from log4shell

**Comment by compucat** [comment]
Hi all - our hosting provider is currently down. We’re aware of the issue and are waiting for them to resolve it. Thanks for your patience!

We are unaware of any log4j vulnerabilities in 4TU projects as we don’t really use Java much, but we’re keeping vigilant nonetheless.

-Alex (compucat)

**Comment by vgmoose** [comment]
These issues are resolved now. It seems the repos removed due to hosting Wii U web exploits on the same domain, possibly as a result of recent security changes by the hosting provider.

The good news is that secondary repos were brought back up on the same domains before the root issue was resolved on the main repos, resulting in much less downtime. These backup repos will be able to be deployed faster if something similar happens in the future!

**Comment by vgmoose** [comment]
The extent of the outage, and future outages, can be monitored on this page:
https://stats.uptimerobot.com/JYZp8iqQOr

Red range spans late Dec 18th through early Dec 22. The secondary repos were deployed late Dec 19 onward, so most main repo downtime was observable Dec 19th, in most timezones:

![datas](https://user-images.githubusercontent.com/2467473/148001814-e0e4c171-ede4-4835-aaf2-a9de2698d587.png)

Uptime percents in this image reflect last 90 days from today, each oval of the bars is one day.
